### PR TITLE
WASI support

### LINKED ISSUE #246: How to test methods that make WASI calls?
Given a file `sample.ts`:

```typescript
import { Console } from "as-wasi";

export function sample(): void {
    Console.log("Foo");
}
```

and a test file `sample.spec.ts`:

```typescript
import { sample } from "../src/sample";

describe("sample", () => {
  it("Should verify something", () => {
    sample();
  });
});
```

I get:
```
TypeError: WebAssembly.Instance(): Import #1 module="wasi_unstable" error: module is not an object or function
    at instantiateSync (/Users/jeffreycharles/scripts/feb27/node_modules/assemblyscript/lib/loader/index.js:307:5)
    at runBinary (/Users/jeffreycharles/scripts/feb27/node_modules/@as-pect/cli/lib/run.js:366:28)
    at /Users/jeffreycharles/scripts/feb27/node_modules/@as-pect/cli/lib/run.js:482:46
    at Object.main (/Users/jeffreycharles/scripts/feb27/node_modules/assemblyscript/cli/asc.js:775:10)
    at /Users/jeffreycharles/scripts/feb27/node_modules/@as-pect/cli/lib/run.js:433:21
    at Array.forEach (<anonymous>)
    at run (/Users/jeffreycharles/scripts/feb27/node_modules/@as-pect/cli/lib/run.js:431:40)
    at Object.asp (/Users/jeffreycharles/scripts/feb27/node_modules/@as-pect/cli/lib/index.js:72:13)
    at Object.<anonymous> (/Users/jeffreycharles/scripts/feb27/node_modules/@as-pect/cli/bin/asp:2:28)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
```

How can I configure `as-pect` so that the `Console.log` call works in the test? Ideally that it prints `Foo` to stdout, less ideally, that the test executes successfully.

### PR DESCRIPTION
**Pull request by jtenner**
Fixes #246 

This should be ready for review and testing. 

CC @willemneal

### CODE REVIEW

File: packages/cli/src/util/IConfiguration.ts [hunk 1]
```diff
@@ -63,4 +63,17 @@ export interface IConfiguration {
    * WASM Memory max size in pages 64kb. Should be positive. Default is disabled or -1.
    */
   memoryMax?: number;
+  /** A wasi configuration. */
+  wasi?:  {
+    /** An array of strings that the WebAssembly application will see as command line arguments. The first argument is the virtual path to the WASI command itself. Default: []. */
+    args: string[];
+    /** An object similar to process.env that the WebAssembly application will see as its environment. Default: {}. */
+    env: any;
```
Comment (willemneal) [inline packages/cli/src/util/IConfiguration.ts]: this will be string indexed correct?  If so, it should be similar to how preopens is defined below.

File: packages/core/src/test/TestContext.ts [hunk 2]
```diff
@@ -57,6 +57,8 @@ export interface ITestContextParameters {
   reporter: IReporter;
   /** The expected snapshot output. */
   snapshots?: Snapshot;
+  /** Wasi parameters. */
+  wasi?: any;
```
Comment (willemneal) [inline packages/core/src/test/TestContext.ts]: Are there not types provide by node for wasi?

File: packages/core/src/test/TestContext.ts [hunk 3]
```diff
@@ -237,141 +256,149 @@ export class TestContext {
...
       this.addResult(node, false);
       this.reporter.onExit(this, node);
       return;
     }
-
-    // We now have the responsibility to run each beforeAll callback before traversing children
-    if (!this.runFunctions(node.beforeAll)) {
+  } else {
+    // gather all the tests and groups, validate program state at this level
+    const success = this.tryCall(node.callback) === 1;
```
Comment (willemneal) [inline packages/core/src/test/TestContext.ts]: shouldn't node.performanceStart be set here and above in the `negated case`?

File: packages/core/src/test/TestContext.ts (hunk 2 above)
Comment (jtenner) [reply packages/core/src/test/TestContext.ts]: @types/node does not have wasi types and I'm perfectly okay with `any` right now as support. We can improve this later.

File: packages/core/src/test/TestContext.ts (hunk 3 above)
Comment (jtenner) [reply packages/core/src/test/TestContext.ts]: node.performanceStart is already set at this point. Yes.

File: packages/cli/src/util/IConfiguration.ts (hunk 1 above)
Comment (jtenner) [reply packages/cli/src/util/IConfiguration.ts]: I'm not trying to have perfect types for this wasi support release. I suppose we should improve these types when `@types/node` updates. Is that an okay compromise?

File: packages/core/src/test/TestContext.ts (hunk 3 above)
Comment (willemneal) [reply packages/core/src/test/TestContext.ts]: No I mean that it seems that you are recording things that aren't the execution of the node.

File: packages/cli/src/util/IConfiguration.ts (hunk 1 above)
Comment (willemneal) [reply packages/cli/src/util/IConfiguration.ts]: Okay then perhaps add a `TODO` comment?

Comment (jtenner) [reply packages/cli/src/util/IConfiguration.ts]: Updated. Please advise.

File: packages/core/src/test/TestContext.ts (hunk 3 above)
Comment (jtenner) [reply packages/core/src/test/TestContext.ts]: Yeah. You're probably right. Can we file an issue and fix this in another pull request?

File: packages/core/src/test/TestContext.ts [hunk 4]
```diff
@@ -540,6 +567,11 @@ export class TestContext {
     /** Override trace completely. */
     finalImports.env.trace = this.trace.bind(this);
 
+    /** Add support for wasi if requested. */
+    if (this.wasi) {
+      finalImports.wasi_snapshot_preview1 = this.wasi.wasiImports;
```
Comment (andrewhassan) [inline packages/core/src/test/TestContext.ts]:
```suggestion
      finalImports.wasi_snapshot_preview1 = this.wasi.wasiImport;
```

I was just testing this branch with Node 13.11.0 and it was breaking on this line. Looks like this should be `wasiImport`, not `wasiImports`.

Comment (jtenner) [reply packages/core/src/test/TestContext.ts]: Thanks for the help. I'm not entirely sure how this should be tested, to be honest. What kind of AssemblyScript code would be appropriate to validate that WASI is functioning?

**Comment by jtenner** [comment]
Docs got updated here: https://app.gitbook.com/@tenner-joshua/s/as-pect/cli-configuration

File: packages/core/src/test/TestContext.ts (hunk 4 above)
Comment (andrewhassan) [reply packages/core/src/test/TestContext.ts]: No problem! I actually don't have any formal tests or anything. I just created a new test that imports `Console` from `as-wasi`, and then manually checked to see that `Console.log('test')` worked.

File: packages/cli/src/util/AspectConfiguration.ts [hunk 5]
```diff
@@ -63,4 +63,19 @@ export interface IConfiguration {
    * WASM Memory max size in pages 64kb. Should be positive. Default is disabled or -1.
    */
   memoryMax?: number;
+  /** A wasi configuration. */
+  wasi?: {
```
Comment (andrewhassan) [inline packages/cli/src/util/AspectConfiguration.ts]: In the case that a user wants to use the default `wasi` config, with this interface, they're forced to actually set the default values (and still be typed correctly). I think it might make sense if each key with a default value was optionally typed like:
```
wasi?: {
  args?: string[];
  
  env?: {
    [envVar: string]: string; // value
  };

  preopens: {
    [virtualPath: string]: string;
  };

  returnOnExit?: boolean;
};
```

Comment (jtenner) [reply packages/cli/src/util/AspectConfiguration.ts]: Thanks for the tip. I think you're correct.

Comment (andrewhassan) [reply packages/cli/src/util/AspectConfiguration.ts]: No problem! Great job on as-pect btw. It's awesome!

File: packages/core/src/test/TestContext.ts (hunk 3 above)
Comment (jtenner) [reply packages/core/src/test/TestContext.ts]: I filed an issue for tightening up the node start and end times to be more accurate. (We are talking less than millisecond timing accuracy, but could technically be made better.
